version: '3.7'

services:
  task-api-dev:
    container_name: task-api-dev
    networks:
      - task-network
    build:
      target: development
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=5001
    expose:
      - 5001
    ports:
      - 5001:5001
    command: npm run dev

  task-api-prod:
    container_name: task-api-prod
    networks:
      - task-network
    build:
      target: production
    environment:
      - NODE_ENV=production
      - PORT=5002
    expose:
      - 5002
    ports:
      - 5002:5002
    command: npm run prod

  task-db:
    container_name: task-db
    image: mysql
    networks:
      - task-network
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: task
      MYSQL_USER: tester
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - task-volume:/var/lib/mysql

networks:
  task-network:
    name: task-network
    driver: bridge

volumes:
  task-volume:
    name: task-volume
